spring:
  application:
    name: token-service
  profiles:
    active: prod

server:
  port: 9003
  shutdown: graceful

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: